console.log("null * 8 = ",(null * 8))
console.log("'five' - 1 = ", ("five" - 1) )
console.log("'5' - 1' = ", ("5" - 1) )
console.log("'5' + 1 = ", ("5" + 1) )
console.log("null + undefined = ", (null + undefined) )
console.log("null == undefined = ", (null == undefined) )
console.log("null == 0 = ", (null == 0) )
console.log("undefined == 0 = ", (undefined == 0) )
console.log("true == 1 = ", (true == 1) )
console.log("false == 0 = ", (false == 0) )
//console.log("false == 0 = ", (false == 0) )
